name: RealRockets
version: 1.0.1
api-version: 1.13
main: com.hadenwatne.realrockets.RealRockets
author: Cynicalvoe
commands:
  rr:
  realrockets:
permissions:
  realrockets.use:
    default: op
  realrockets.dropore:
    default: op